language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: AWS_ACCESS_KEY
  secret_access_key:
    secure: AWS_SECRET_KEY
  region: "us-east-2"
  app: "django-app-polls"
  env: "polls-app-env"
  bucket_name: "the-target-S3-bucket"