dist: focal
language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
#  - python manage.py collectstatic --noinput
script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test
  - coverage report
after_script:
  - coveralls

env:
  global:
    - COVERALLS_REPO_TOKEN=6COi2NHZixOMoz9pRoxtHe9ArW1liolVQ

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_SECRET_KEY
  region: us-east-1
  app: sample-app1
  env: sampel-app1-env
  bucket_name: elasticbeanstalk-us-east-1-545009869282
  on:
    branch: main

